Create fr.js
tmoitie/iRacing-week-planner pull request #44
Opened 2020-08-20 19:30 UTC by OpakoDev

Some translations might be inaccurate but most of them are correct.
I also didn't edit the dates format as I didn't exactly know how can I edit them and t he "set times" field as I didn't see where does it go to notice the exact translation ^^

2020-08-25 00:26 UTC, tmoitie commented
Set Times is when a race isn't regular - it goes off on "set times" - it appears in the "Race times" column. I've screenshotted an example:
![Screenshot 2020-08-25 at 01 25 03](https://user-images.githubusercontent.com/985557/91109100-deb02480-e671-11ea-8607-109f5ef0189c.png)

Regarding the date, just leave the bit in the curly brackets as is. Merci beaçoup for your time and effort!

2020-09-29 07:39 UTC, remigarcia requested changes
Hello there :) I was starting to translate it when I saw this PR. I then allowed myself to review it.
Saw one untranslated message, some quotes errors and spell checks.

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +    'Purchase guide': 'Guide d'achats',
```suggestion
    'Purchase guide': 'Guide d\'achats',
```

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +    'Set favorite series': 'Séries favories',
```suggestion
    'Set favorite series': 'Séries favorites',
```

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +    'Favorite series only': 'Séries favories seulement',
```suggestion
    'Favorite series only': 'Séries favorites seulement',
```

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +    'Favorite cars only': 'Voitures favories seulement',
```suggestion
    'Favorite cars only': 'Voitures favorites seulement',
```

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +    'Columns': 'Colomnes',
```suggestion
    'Columns': 'Colonnes',
```

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +      'Use the checkbox to set the content you own, and use the star to set your favourite content.',
```suggestion
      'Utilisez les cases à cocher pour enregistrer le contenu que vous possédez et utilisez l\'étoile pour enregistrer vos contenus favoris.',
```

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +    'Select all oval': 'Sélectionner tous les ovaux',
```suggestion
    'Select all oval': 'Sélectionner tous les ovales',
```

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +    'Choose favorite series': 'Sélectionner les séries favories',
```suggestion
    'Choose favorite series': 'Sélectionner les séries favorites',
```

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +    'Purchase Guide': 'Guide d'achat',
```suggestion
    'Purchase Guide': 'Guide d\'achat',
```

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +      'Cet outil a été créé par <1>tmoitie</1> (<3>Tom Moitié</3> sur iRacing). N'hésitez pas à me contacter sur Twitter ou iRacing si vous avez un retour à faire ou des questions à poser. Le code so
```suggestion
      'Cet outil a été créé par <1>tmoitie</1> (<3>Tom Moitié</3> sur iRacing). N\'hésitez pas à me contacter sur Twitter ou iRacing si vous avez un retour à faire ou des questions à poser. Le code source est hébergé publiquement sur <5>Github</5>. Merci !',
```

2020-09-29 07:39 UTC, remigarcia commented on translations/fr.js
> +    'These unowned tracks from your favorite series appear multiple times for this season. You can purchase these tracks with the direct link.': 'Ces circuits non possédés apparaissent plusieurs fois
```suggestion
    'These unowned tracks from your favorite series appear multiple times for this season. You can purchase these tracks with the direct link.': 'Ces circuits non possédés apparaissent plusieurs fois dans vos séries favorites cette saison. Vous pouvez les acheter via le lien direct.',
```

2020-10-12 12:25 UTC, tmoitie commented
Thanks both! I'm merging what we've got here and left a comment filled with everything left to translate (stuff I've added since, sorry!). Merci beauçoup !

2020-10-12 12:25 UTC, merged